create table if not exists waitlist_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  phone text not null unique,
  focus text not null,
  challenge text not null,
  rituals text,
  created_at timestamptz not null default now()
);

create table if not exists questionnaire_results (
  id bigint generated by default as identity primary key,
  result text not null,
  gut_score integer not null,
  skin_score integer not null,
  match_score integer not null,
  answers_json jsonb not null,
  created_at timestamptz not null default now()
);